//getting all buttons and icons
const flipBtn = document.querySelector('.flip-btn');
const copyBtn = document.querySelector('.copy-btn');
const colorCode=document.querySelector('.color-code');
const toggleMode = document.querySelector('.toggle-mode');
//setting to hexmode initially
let isHexMode= true;
console.log(colorCode,copyBtn,flipBtn,toggleMode);
//function to get hex code;
const getRandomHexColor = ()=>
{
    const hex =`#${Math.floor(Math.random()*16772335).toString(16)}`;//will generate 7digit random number which will be accompanied with #
    return hex.padEnd(7,'0'); //if no value is generated by random then it will get default value of 7 '0's eg #0000000
    
}
const getRandomRGBColor =()=>
{
    const r = Math.floor(Math.random()*256); //generate a random red green blue value 
    const g = Math.floor(Math.random()*256);
    const b = Math.floor(Math.random()*256);
    return `rgb(${r},${g},${b})` //the generated rgb value is passed to rgbfuntion of css and that is returned
}
const changeColor = ()=>
{
    const newColor = isHexMode ? getRandomHexColor() : getRandomRGBColor(); //toggle button if hexmode true it call hexgen or it will call rgbgen()
    document.body.style.backgroundColor=newColor; //setting generated to var
    colorCode.innerHTML=newColor; //setting that generated color body background color;
}
const toggleRgb = ()=>
{
    isHexMode = !isHexMode;
    toggleMode.textContent=isHexMode ? "🔄️Switch to RGB" : "🔄️Swith to HEX!" //toggle switch hexmode if hexmode is true it will set it to false if false set it to true.

} 
const copyToClipboard = ()=>
{
    navigator.clipboard.writeText(colorCode.textContent); //inbuilt which copy the text to clipbooard so we giving the colorcode to this so that color-code will be copied to textboard.
    alert( `copied color code:${colorCode.textContent}`);
}
//creating eventlisteners.
flipBtn.addEventListener('click',changeColor);
toggleMode.addEventListener('click',toggleRgb);
copyBtn.addEventListener('click',copyToClipboard);
